server:
  port: 8300

spring:
  application:
    name: gateway
  cloud:
    # nacos 配置 --------------------------
    nacos:
      discovery:
        server-addr: 192.168.111.100:8848 #nacos 主机ip：端口
    # gateway 网关 ------------------------
    gateway:
      discovery:
        locator:
          enabled: true #使用服务名发现路由
      routes:
        # ------------------------ service-vod 模块 -----------------------------
        # 注意，注意，注意：动态路由下，服务名称不能用下划线，而且服务名称不要与断言前缀相同，也就是不与请求路径相同
        #
        - id: service-vod #路由的ID，没有固定规则但要求唯一，建议配合服务名'
          uri: lb://service-vod # 开启动态路由，实现负载均衡
          predicates: # 对控制层路径的匹配
            - Path=/vod/**,/*/vod/**
#          filters:
#            - StripPrefix=1
        # ------------------------  service-order 模块 -----------------------------
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/order/**
        # ------------------------  service-activity 模块 -----------------------------
        - id: service-activity
          uri: lb://service-activity
          predicates:
            - Path=/activity/**
        # ------------------------  service-user 模块 -----------------------------
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/**
        # ------------------------  service-wechat 模块 -----------------------------
        - id: service-wechat
          uri: lb://service-wechat
          predicates:
            - Path=/wechat/**


